import {
    Activity,
    Archive,
    ArrowLeftRight,
    Banknote,
    BarChart3,
    BookMarked,
    Bot,
    Brain,
    CalendarCheck,
    CalendarDays,
    ClipboardCheck,
    ClipboardList,
    DoorOpen,
    FileBarChart,
    FolderTree,
    Layers,
    LayoutDashboard,
    LayoutGrid,
    ListTodo,
    Megaphone,
    Package,
    PackageSearch,
    Receipt,
    School,
    Settings,
    Shield,
    ShoppingCart,
    Sparkles,
    Trophy,
    TriangleAlert,
    User,
    UserCheck,
    UserCircle,
    UserCog,
    Users,
    Video,
    Wallet,
    type LucideIcon,
} from 'lucide-react';

const NAV_ICONS: Record<string, LucideIcon> = {
    activity: Activity,
    brain: Brain,
    archive: Archive,
    'alert-triangle': TriangleAlert,
    banknote: Banknote,
    bot: Bot,
    'calendar-days': CalendarDays,
    receipt: Receipt,
    'layout-dashboard': LayoutDashboard,
    school: School,
    'graduation-cap': School,
    layers: Layers,
    'book-marked': BookMarked,
    'layout-grid': LayoutGrid,
    'list-todo': ListTodo,
    megaphone: Megaphone,
    'door-open': DoorOpen,
    users: Users,
    user: User,
    'user-circle': UserCircle,
    'clipboard-list': ClipboardList,
    wallet: Wallet,
    package: Package,
    'package-search': PackageSearch,
    'folder-tree': FolderTree,
    'arrow-left-right': ArrowLeftRight,
    sparkles: Sparkles,
    'shopping-cart': ShoppingCart,
    'calendar-check': CalendarCheck,
    'clipboard-check': ClipboardCheck,
    'user-check': UserCheck,
    'file-bar-chart': FileBarChart,
    'bar-chart-3': BarChart3,
    settings: Settings,
    shield: Shield,
    'user-cog': UserCog,
    trophy: Trophy,
    video: Video,
};

export function intranetNavIcon(key?: string | null): LucideIcon {
    if (key && NAV_ICONS[key]) {
        return NAV_ICONS[key];
    }
    return LayoutDashboard;
}

export function statsIcon(key: string): LucideIcon {
    return intranetNavIcon(key);
}
