sonar.projectKey=sistema-colegio-horizonte
sonar.projectName=Sistema Colegio Horizonte
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=app,routes,database,resources/js,bootstrap,config
sonar.tests=tests
sonar.php.file.suffixes=php
sonar.javascript.file.suffixes=js,jsx
sonar.typescript.file.suffixes=ts,tsx

sonar.exclusions=**/vendor/**,**/node_modules/**,**/public/build/**,**/storage/**,**/bootstrap/cache/**,**/*.blade.php,**/cypress/**
sonar.test.inclusions=tests/**/*
sonar.coverage.exclusions=**/tests/**,**/database/migrations/**,**/database/seeders/**,**/database/factories/**,**/routes/**
sonar.php.coverage.reportPaths=build/coverage/clover.xml
